INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit) VALUES
('RECIPE_ID_FOR_Beard_Oil', 'INGREDIENT_ID_FOR_Jojoba_Oil', '40%', '12g'),
('RECIPE_ID_FOR_Beard_Oil', 'INGREDIENT_ID_FOR_Essential_Oils', '1%', '0.3g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Beeswax', '33%', '19.8g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Unrefined_Shea_Butter', '20%', '12g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Cocoa_Butter', '22%', '13.2g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Unrefined_Mango_Butter', '15%', '9g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Lanolin', '10%', '6g'),
('RECIPE_ID_FOR_Beard_Balm', 'INGREDIENT_ID_FOR_Arrowroot_Powder', '5%', '3g'),
('RECIPE_ID_FOR_Mustache_Wax', 'INGREDIENT_ID_FOR_Beeswax', '60%', '30g'),
('RECIPE_ID_FOR_Mustache_Wax', 'INGREDIENT_ID_FOR_Cocoa_Butter', '25%', '12.5g'),
('RECIPE_ID_FOR_Mustache_Wax', 'INGREDIENT_ID_FOR_Coconut_Oil', '15%', '7.5g'),
('RECIPE_ID_FOR_Foaming_Hand_Soap', 'INGREDIENT_ID_FOR_Unscented_Castile_Soap', '25%', '60ml'),
('RECIPE_ID_FOR_Foaming_Hand_Soap', 'INGREDIENT_ID_FOR_Water', '70%', '168ml'),
('RECIPE_ID_FOR_Foaming_Hand_Soap', 'INGREDIENT_ID_FOR_Sweet_Almond_Oil', '4%', '9.6ml'),
('RECIPE_ID_FOR_Foaming_Hand_Soap', 'INGREDIENT_ID_FOR_Essential_Oils', '1%', '2.4ml'),
('RECIPE_ID_FOR_Hand_Cream', 'INGREDIENT_ID_FOR_Unrefined_Shea_Butter', '30%', '60g'),
('RECIPE_ID_FOR_Hand_Cream', 'INGREDIENT_ID_FOR_Cocoa_Butter', '15%', '30g'),
('RECIPE_ID_FOR_Hand_Cream', 'INGREDIENT_ID_FOR_Almond_Oil', '40%', '80ml'),
('RECIPE_ID_FOR_Hand_Cream', 'INGREDIENT_ID_FOR_Beeswax', '15%', '30g'),
('RECIPE_ID_FOR_Hand_Cream', 'INGREDIENT_ID_FOR_Essential_Oils', '', '20-30 drops'),
('RECIPE_ID_FOR_Hair_Rinse', 'INGREDIENT_ID_FOR_Apple_Cider_Vinegar', '15%', '30ml'),
('RECIPE_ID_FOR_Hair_Rinse', 'INGREDIENT_ID_FOR_Water', '85%', '170ml'),
('RECIPE_ID_FOR_Hair_Rinse', 'INGREDIENT_ID_FOR_Essential_Oils', '', '5-10 drops');